; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

; [env:native]
; platform = native
; build_flags = 
; 	-DUNIT_TEST
; 	-DNATIVE_BUILD
; 	-std=c++17
; lib_deps = 
; 	${env:esp32dev.lib_deps}
; 	throwtheswitch/Unity@^2.5.2
; 	knolleary/PubSubClient@^2.8
; test_framework = unity
; test_ignore = test_native/*

[env:esp32_test]
platform = espressif32
board = esp32dev
framework = arduino
upload_port = COM5
monitor_port = COM5
monitor_speed = 115200
test_framework = unity
build_flags = 
	-DUNIT_TEST
	-DCORE_DEBUG_LEVEL=3
	-I include
lib_deps = 
	throwtheswitch/Unity@^2.5.2
	tzapu/WiFiManager @ ^2.0.17
	bblanchon/ArduinoJson @ ^7.2.0
	openenergymonitor/EmonLib@^1.1.0
	h2zero/NimBLE-Arduino@^2.3.6
	knolleary/PubSubClient@^2.8
board_build.partitions = min_spiffs.csv
test_filter = test_embedded/*
test_build_src = no

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
upload_port = COM5
monitor_port = COM5
board_build.partitions = min_spiffs.csv
monitor_speed = 115200
lib_deps = 
	tzapu/WiFiManager @ ^2.0.17
	bblanchon/ArduinoJson @ ^7.2.0
	openenergymonitor/EmonLib@^1.1.0
	knolleary/PubSubClient@^2.8
build_flags = 
	-DCORE_DEBUG_LEVEL=4
	-DDEBUG_ESP_PORT=Serial
build_src_flags = 
	-Wall
	-Wextra
	-Wformat
	-Wformat-security
