//
// XXXXXXXXXXXXXXXXXXXX FOR FUTURE USE WITH VPS BROKER XXXXXXXXXXXXXXXXXXXX
//
// #ifndef CERTIFICATES_H
// #define CERTIFICATES_H
//
// // ISRG Root X1 (Let's Encrypt)
// static const char MQTT_CA_CERT[] PROGMEM = R"EOF(
// -----BEGIN CERTIFICATE-----
// MIIDfTCCAmWgAwIBAgIUHsb+WtDhkBCb3VM5d75gene1NQIwDQYJKoZIhvcNAQEL
// BQAwTjELMAkGA1UEBhMCVVMxDTALBgNVBAgMBFRlc3QxDTALBgNVBAcMBFRlc3Qx
// DzANBgNVBAoMBlRlc3RDQTEQMA4GA1UEAwwHTVFUVC1DQTAeFw0yNTExMjkxMTQ4
// NTVaFw0yNjExMjkxMTQ4NTVaME4xCzAJBgNVBAYTAlVTMQ0wCwYDVQQIDARUZXN0
// MQ0wCwYDVQQHDARUZXN0MQ8wDQYDVQQKDAZUZXN0Q0ExEDAOBgNVBAMMB01RVFQt
// Q0EwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQCYVEFsETHKYFO9NcRy
// Cwsev2f/JVc3Pg7teubFxjupJRbaNc1SSBFSiOQv4wXHLNxRUO+e20x/MCLynybO
// hFspfBMPMKMhGCZRp3aXaO+PZsfmuRjcX+G/U6jTkPV3pf4bP3Czjwnr+9YECiuc
// TZpBZANZr2mumjgEThEwni00hBth/I8TQs8m1HumiGU4R50VDIc/FBtBo8GiEZcd
// 8f68d3zfad5tzf7ayd7EMRjYFy/Ztru782YhIFfuaD69+PkspeSgNGGbjZHthSJW
// 94X+kRKdRIdFDJmovlshGeMXcm/EtWxHGyiUakVA/9s+wj6x2LBCv60qS1UOP487
// uXpfAgMBAAGjUzBRMB0GA1UdDgQWBBRyz9TPxwnsuspIxE/M/fOTFsxEzzAfBgNV
// HSMEGDAWgBRyz9TPxwnsuspIxE/M/fOTFsxEzzAPBgNVHRMBAf8EBTADAQH/MA0G
// CSqGSIb3DQEBCwUAA4IBAQBouTwyZ+nYYxQJUYTla2VpBXSmI5DdCzPFSgKK4m2R
// GNIrdSgxadg81PRCWVS9UHz2G1sLsTUqQEhJBNXLWZmWNBPzD/FlmOHbHDTW6/2U
// d/mS1S8ID4j+NHdb9c9tkC2GrUxS7cKrOunVjkn9edIkDK/iehmd2BX8jcTeHn8p
// BfrLgcPNsYytkGM7w1JfqtVB8xtockhBtNKMSozlkYJ9pfl5P7tq5TNWKYBrJV24
// AAYcJMJPPtyZvWtV8d0CnB8vCB8kifErTlzJmQYy9Qepe0Ykdr+iPNgMV1/3zfoH
// UPyP0t+9wYxxZzlTotU8CRQ9OkrJCEmotWPsK3Pbb2G3
// -----END CERTIFICATE-----
// )EOF";
//
// #endif // CERTIFICATES_H
